{% set name = "pydata-sphinx-theme" %}
{% set version = "0.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b04e9f09cf1efdf814f0a565e4ba2c925282ba2e528d55f663bbd4176fc06c9e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - sphinx

test:
  imports:
    - pydata_sphinx_theme

about:
  home: https://github.com/pandas-dev/pydata-sphinx-theme
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Bootstrap-based Sphinx theme from the PyData community
  doc_url: https://pydata-sphinx-theme.readthedocs.io/
  dev_url: https://github.com/pandas-dev/pydata-sphinx-theme

extra:
  recipe-maintainers:
    - jorisvandenbossche
