{% set name = "pydata-sphinx-theme" %}
{% set version = "0.16.1" %}
package:
  name: pydata-sphinx-theme
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pydata_sphinx_theme-{{ version }}.tar.gz
  sha256: a08b7f0b7f70387219dc659bff0893a7554d5eb39b59d3b8ef37b8401b7642d7
  patches:
    - 000_set_nodejs_version.patch   # [linux]

build:
  number: 0
  skip: true   #[py<39 or s390x]
  script:
    - export STB_USE_SYSTEM_NODE=1  # [linux]
    - {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv
requirements:
  host:
    - pip
    - python
    - nodejs 20.17.0
    - sphinx-theme-builder 0.2.0b2
  run:
    - sphinx >=6.1
    - beautifulsoup4
    - docutils !=0.17.0
    - babel
    - pygments >=2.7
    - accessible-pygments
    - typing-extensions
    - packaging
    - python

test:
  imports:
    - pydata_sphinx_theme
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pydata/pydata-sphinx-theme
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Bootstrap-based Sphinx theme from the PyData community
  description: |

  doc_url: https://pydata-sphinx-theme.readthedocs.io/
  dev_url: https://github.com/pydata/pydata-sphinx-theme

extra:
  recipe-maintainers:
    - jorisvandenbossche
    - bollwyvl
