{% set name = "pydata-sphinx-theme" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 41dc4ef4305ed837d414aeac4c1d5fb8f6d2b9f4d8c90fd8e902ede9e78b693b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - sphinx

test:
  imports:
    - pydata_sphinx_theme

about:
  home: https://github.com/pandas-dev/pydata-sphinx-theme
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Bootstrap-based Sphinx theme from the PyData community
  doc_url: https://pydata-sphinx-theme.readthedocs.io/
  dev_url: https://github.com/pandas-dev/pydata-sphinx-theme

extra:
  recipe-maintainers:
    - jorisvandenbossche
