{% set version = "0.16.1" %}

package:
  name: pydata-sphinx-theme
  version: {{ version }}

source:
  url: https://github.com/pydata/pydata-sphinx-theme/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 1759e12524b440d136228086206fbd23c3cf8007a64d3cecd7eda492f85617d3

build:
  number: 0
  skip: true   #[py<39]
  script:
    - {{ PYTHON }} -m pip install --find-links . --no-index --ignore-installed --no-deps pydata-sphinx-theme
    - cd {{ RECIPE_DIR }} && {{ PYTHON }} collect_licenses.py

requirements:
  host:
    - pip
    - python
    - sphinx-theme-builder 0.2.0b2
  run:
    - sphinx >=6.1
    - beautifulsoup4
    - docutils !=0.17.0
    - babel
    - pygments >=2.7
    - accessible-pygments
    - typing-extensions
    - packaging
    - python

test:
  source_files:
    - src/tests
  imports:
    - pydata_sphinx_theme
  commands:
    - pip check
  requires:
    - sphinx
    - pip
    - pytest-cov
    - pytest-regressions
    - python
    # tests in run_test.py

about:
  home: https://github.com/pydata/pydata-sphinx-theme
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - src/LICENSE
    - third-party-licenses/font-awesome-LICENSE.txt
  summary: Bootstrap-based Sphinx theme from the PyData community
  doc_url: https://pydata-sphinx-theme.readthedocs.io/
  dev_url: https://github.com/pydata/pydata-sphinx-theme

extra:
  recipe-maintainers:
    - jorisvandenbossche
    - bollwyvl
