{% set version = "0.9.0" %}
{% set cov_fail_under = 78 %}

package:
  name: pydata-sphinx-theme
  version: {{ version }}

source:
  - url: https://pypi.io/packages/py3/p/pydata-sphinx-theme/pydata_sphinx_theme-{{ version }}-py3-none-any.whl
    sha256: b22b442a6d6437e5eaf0a1f057169ffcb31eaa9f10be7d5481a125e735c71c12
  - folder: src
    url: https://github.com/pydata/pydata-sphinx-theme/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 1aaa1cf3261c46d1ac00c38feaa9fc7d5f22ba7e072f346970dabd772b7640c2

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -m pip install --find-links . --no-index --ignore-installed --no-deps pydata-sphinx-theme
    - cd {{ RECIPE_DIR }} && {{ PYTHON }} collect_licenses.py

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - beautifulsoup4
    - docutils !=0.17.0
    - python >=3.7
    - sphinx

test:
  source_files:
    - src/tests
  imports:
    - pydata_sphinx_theme
  commands:
    - pip check
    - cd src/tests
    - pytest -vv --cov=pydata_sphinx_theme --cov-branch --cov-report=term-missing:skip-covered --no-cov-on-fail --cov-fail-under={{ cov_fail_under }}
  requires:
    # probably _compatible_ with older versions of sphinx, but would fail tests
    # see https://github.com/pydata/pydata-sphinx-theme/issues/446
    - sphinx >=4
    - jupyter_sphinx !=0.3.1
    - numpydoc
    - pandas
    - pip
    - plotly
    - pytest-cov
    - pytest-regressions
    - recommonmark
    - sphinx-thebe
    - xarray

about:
  home: https://github.com/pydata/pydata-sphinx-theme
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - src/LICENSE
    - third-party-licenses/font-awesome-LICENSE.txt
  summary: Bootstrap-based Sphinx theme from the PyData community
  doc_url: https://pydata-sphinx-theme.readthedocs.io/
  dev_url: https://github.com/pydata/pydata-sphinx-theme

extra:
  recipe-maintainers:
    - jorisvandenbossche
    - bollwyvl
