{% set name = "pydata-sphinx-theme" %}
{% set version = "0.7.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: 671df35fcdd290eafbd23d0595e6d359dbe90b2e64e6c3f4dc88276eed4a065e
  - folder: src
    url: https://github.com/pydata/pydata-sphinx-theme/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 825096e75b35a55bcb05171e4a0efc22ad49527ce7a91ae961f433157b749e84

build:
  number: 0
  noarch: python
  script: cd dist && {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - sphinx
    - beautifulsoup4
    - docutils

test:
  source_files:
    - src/tests
  imports:
    - pydata_sphinx_theme
  commands:
    - pip check
    - cd src/tests
    - pytest -vv --cov pydata_sphinx_theme --cov-branch --cov-fail-under=73 --cov-report term-missing:skip-covered --no-cov-on-fail
  requires:
    - jupyter_sphinx !=0.3.1
    - numpydoc
    - pandas
    - pip
    - plotly
    - pytest-cov
    - pytest-regressions
    - recommonmark
    - sphinx-thebe
    - xarray

about:
  home: https://github.com/pydata/pydata-sphinx-theme
  license: BSD-3-Clause
  license_family: BSD
  license_file: dist/LICENSE
  summary: Bootstrap-based Sphinx theme from the PyData community
  doc_url: https://pydata-sphinx-theme.readthedocs.io/
  dev_url: https://github.com/pydata/pydata-sphinx-theme

extra:
  recipe-maintainers:
    - jorisvandenbossche
    - bollwyvl
